WMO_CODES = {
    0: "☼ Clear sky",
    1: "🌤 Mainly clear",
    2: "⛅ Partly cloudy",
    3: "☁ Overcast",
    45: "Fog",
    48: "Depositing rime fog",
    51: "☂ Light drizzle",
    53: "☔ Fair drizzle",
    55: "🌦 Dense drizzle",
    56: "Freezing drizzle: Light intensity",
    57: "Freezing drizzle: Dense intensity",
    61: "☔ Light rain",
    63: "🌧 Moderate rain",
    65: "🌧 Heavy rain",
    66: "Freezing rain: Light intensity",
    67: "Freezing rain: Heavy intensity",
    71: "Snow fall: Slight intensity",
    73: "Snow fall: Moderate intensity",
    75: "Snow fall: Heavy intensity",
    77: "Snow grains",
    80: "🌦 Light showers",
    81: "🌦 Moderate showers",
    82: "🌦 Violent showers",
    85: "Snow showers: Slight intensity",
    86: "Snow showers: Heavy intensity",
    95: "⛈ Thunderstorm",
    96: "⛈ Thunderstorm with hail",
    97: "⛈ Heavy thunderstorm",
    98: "⛈ Heavy thunderstorm with hail"
}
